# Generated by Django 4.0 on 2022-03-09 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_auction_id_alter_bid_id_alter_category_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='category',
            field=models.ForeignKey(blank='False', on_delete=django.db.models.deletion.DO_NOTHING, related_name='categories', to='auctions.category'),
        ),
    ]
